<S> ::= <RUN_CODE_RULES_DEFAULT_ACTION> ### <ON_SCANNED_ROBOT_CODE_RULES_DEFAULT_ACTION> ### <ON_HIT_BY_BULLET_CODE_RULES_DEFAULT_ACTION> [1]

<RUN_CODE_RULES_DEFAULT_ACTION> ::= <RUN_CODE_RULES> default <RUN_CODE_CONSEQUENTS> [1]
<RUN_CODE_RULES> ::= <RUN_CODE_RULE> [0.2]
<RUN_CODE_RULES> ::= <RUN_CODE_RULE> <RUN_CODE_RULES> [0.8]
<RUN_CODE_RULE> ::= if <RUN_CODE_ANTECEDENTS> then <RUN_CODE_CONSEQUENTS> [1]
<RUN_CODE_ANTECEDENTS> ::= <RUN_CODE_ANTECEDENT> [0.2]
<RUN_CODE_ANTECEDENTS> ::= ( <RUN_CODE_ANTECEDENT> <RUN_CODE_OPR_ANTECEDENTS> <RUN_CODE_ANTECEDENTS> ) [0.5]
<RUN_CODE_ANTECEDENTS> ::= not ( <RUN_CODE_ANTECEDENTS> ) [0.3]
<RUN_CODE_ANTECEDENT> ::= robot_x <RUN_CODE_OPR_CLAUSE> <RUN_CODE_CLAUSE_ROBOT_X> [0.25]
<RUN_CODE_ANTECEDENT> ::= robot_y <RUN_CODE_OPR_CLAUSE> <RUN_CODE_CLAUSE_ROBOT_Y> [0.25]
<RUN_CODE_ANTECEDENT> ::= robot_heading <RUN_CODE_OPR_CLAUSE> <RUN_CODE_CLAUSE_ROBOT_HEADING> [0.25]
<RUN_CODE_ANTECEDENT> ::= robot_velocity <RUN_CODE_OPR_CLAUSE> <RUN_CODE_CLAUSE_ROBOT_VELOCITY> [0.25]
<RUN_CODE_OPR_CLAUSE> ::= > [0.5]
<RUN_CODE_OPR_CLAUSE> ::= < [0.5]
<RUN_CODE_CLAUSE_ROBOT_X> ::= 0 [0.2]
<RUN_CODE_CLAUSE_ROBOT_X> ::= 200 [0.2]
<RUN_CODE_CLAUSE_ROBOT_X> ::= 400 [0.2]
<RUN_CODE_CLAUSE_ROBOT_X> ::= 600 [0.2]
<RUN_CODE_CLAUSE_ROBOT_X> ::= 800 [0.2]
<RUN_CODE_CLAUSE_ROBOT_Y> ::= 0 [0.2]
<RUN_CODE_CLAUSE_ROBOT_Y> ::= 150 [0.2]
<RUN_CODE_CLAUSE_ROBOT_Y> ::= 300 [0.2]
<RUN_CODE_CLAUSE_ROBOT_Y> ::= 450 [0.2]
<RUN_CODE_CLAUSE_ROBOT_Y> ::= 600 [0.2]
<RUN_CODE_CLAUSE_ROBOT_HEADING> ::= 0 [0.25]
<RUN_CODE_CLAUSE_ROBOT_HEADING> ::= 90 [0.25]
<RUN_CODE_CLAUSE_ROBOT_HEADING> ::= 180 [0.25]
<RUN_CODE_CLAUSE_ROBOT_HEADING> ::= 270 [0.25]
<RUN_CODE_CLAUSE_ROBOT_VELOCITY> ::= -8 [0.2]
<RUN_CODE_CLAUSE_ROBOT_VELOCITY> ::= -4 [0.2]
<RUN_CODE_CLAUSE_ROBOT_VELOCITY> ::= 0 [0.2]
<RUN_CODE_CLAUSE_ROBOT_VELOCITY> ::= 4 [0.2]
<RUN_CODE_CLAUSE_ROBOT_VELOCITY> ::= 8 [0.2]
<RUN_CODE_OPR_ANTECEDENTS> ::= and [0.5]
<RUN_CODE_OPR_ANTECEDENTS> ::= or [0.5]
<RUN_CODE_CONSEQUENTS> ::= ahead <DISTANCE_VALUE> [0.25]
<RUN_CODE_CONSEQUENTS> ::= back <DISTANCE_VALUE> [0.15]
<RUN_CODE_CONSEQUENTS> ::= turn_right <DEGREES_VALUE> [0.25]
<RUN_CODE_CONSEQUENTS> ::= turn_left <DEGREES_VALUE> [0.25]
<RUN_CODE_CONSEQUENTS> ::= do_nothing [0.1]
<DISTANCE_VALUE> ::= 20 [0.2]
<DISTANCE_VALUE> ::= 40 [0.2]
<DISTANCE_VALUE> ::= 60 [0.2]
<DISTANCE_VALUE> ::= 80 [0.2]
<DISTANCE_VALUE> ::= 100 [0.2]
<DEGREES_VALUE> ::= 5 [0.25]
<DEGREES_VALUE> ::= 15 [0.25]
<DEGREES_VALUE> ::= 30 [0.25]
<DEGREES_VALUE> ::= 45 [0.25]

<ON_SCANNED_ROBOT_CODE_RULES_DEFAULT_ACTION> ::= <ON_SCANNED_ROBOT_CODE_RULES> default <ON_SCANNED_ROBOT_CODE_CONSEQUENTS> [1]
<ON_SCANNED_ROBOT_CODE_RULES> ::= <ON_SCANNED_ROBOT_CODE_RULE> [0.2]
<ON_SCANNED_ROBOT_CODE_RULES> ::= <ON_SCANNED_ROBOT_CODE_RULE> <ON_SCANNED_ROBOT_CODE_RULES> [0.8]
<ON_SCANNED_ROBOT_CODE_RULE> ::= if <ON_SCANNED_ROBOT_CODE_ANTECEDENTS> then <ON_SCANNED_ROBOT_CODE_CONSEQUENTS> [1]
<ON_SCANNED_ROBOT_CODE_ANTECEDENTS> ::= <ON_SCANNED_ROBOT_CODE_ANTECEDENT> [0.2]
<ON_SCANNED_ROBOT_CODE_ANTECEDENTS> ::= ( <ON_SCANNED_ROBOT_CODE_ANTECEDENT> <ON_SCANNED_ROBOT_CODE_OPR_ANTECEDENTS> <ON_SCANNED_ROBOT_CODE_ANTECEDENTS> ) [0.5]
<ON_SCANNED_ROBOT_CODE_ANTECEDENTS> ::= not ( <ON_SCANNED_ROBOT_CODE_ANTECEDENTS> ) [0.3]
<ON_SCANNED_ROBOT_CODE_ANTECEDENT> ::= distance <ON_SCANNED_ROBOT_CODE_OPR_CLAUSE> <ON_SCANNED_ROBOT_CODE_CLAUSE_DISTANCE> [0.34]
<ON_SCANNED_ROBOT_CODE_ANTECEDENT> ::= energy <ON_SCANNED_ROBOT_CODE_OPR_CLAUSE> <ON_SCANNED_ROBOT_CODE_CLAUSE_ENERGY> [0.33]
<ON_SCANNED_ROBOT_CODE_ANTECEDENT> ::= bearing <ON_SCANNED_ROBOT_CODE_OPR_CLAUSE> <ON_SCANNED_ROBOT_CODE_CLAUSE_BEARING> [0.33]
<ON_SCANNED_ROBOT_CODE_OPR_CLAUSE> ::= > [0.5]
<ON_SCANNED_ROBOT_CODE_OPR_CLAUSE> ::= < [0.5]
<ON_SCANNED_ROBOT_CODE_CLAUSE_DISTANCE> ::= 100 [0.25]
<ON_SCANNED_ROBOT_CODE_CLAUSE_DISTANCE> ::= 300 [0.25]
<ON_SCANNED_ROBOT_CODE_CLAUSE_DISTANCE> ::= 500 [0.25]
<ON_SCANNED_ROBOT_CODE_CLAUSE_DISTANCE> ::= 700 [0.25]
<ON_SCANNED_ROBOT_CODE_CLAUSE_ENERGY> ::= 10 [0.2]
<ON_SCANNED_ROBOT_CODE_CLAUSE_ENERGY> ::= 30 [0.2]
<ON_SCANNED_ROBOT_CODE_CLAUSE_ENERGY> ::= 50 [0.2]
<ON_SCANNED_ROBOT_CODE_CLAUSE_ENERGY> ::= 70 [0.2]
<ON_SCANNED_ROBOT_CODE_CLAUSE_ENERGY> ::= 90 [0.2]
<ON_SCANNED_ROBOT_CODE_CLAUSE_BEARING> ::= -120 [0.2]
<ON_SCANNED_ROBOT_CODE_CLAUSE_BEARING> ::= -60 [0.2]
<ON_SCANNED_ROBOT_CODE_CLAUSE_BEARING> ::= 0 [0.2]
<ON_SCANNED_ROBOT_CODE_CLAUSE_BEARING> ::= 60 [0.2]
<ON_SCANNED_ROBOT_CODE_CLAUSE_BEARING> ::= 120 [0.2]
<ON_SCANNED_ROBOT_CODE_OPR_ANTECEDENTS> ::= and [0.5]
<ON_SCANNED_ROBOT_CODE_OPR_ANTECEDENTS> ::= or [0.5]
<ON_SCANNED_ROBOT_CODE_CONSEQUENTS> ::= fire <POWER_VALUE> [0.45]
<ON_SCANNED_ROBOT_CODE_CONSEQUENTS> ::= do_nothing [0.1]
<ON_SCANNED_ROBOT_CODE_CONSEQUENTS> ::= ahead <ON_SCANNED_DISTANCE_VALUE> [0.15]
<ON_SCANNED_ROBOT_CODE_CONSEQUENTS> ::= turn_right <ON_SCANNED_DEGREES_VALUE> [0.15]
<ON_SCANNED_ROBOT_CODE_CONSEQUENTS> ::= turn_left <ON_SCANNED_DEGREES_VALUE> [0.15]
<POWER_VALUE> ::= 0.5 [0.2]
<POWER_VALUE> ::= 1 [0.2]
<POWER_VALUE> ::= 2 [0.2]
<POWER_VALUE> ::= 2.5 [0.2]
<POWER_VALUE> ::= 3 [0.2]
<ON_SCANNED_DISTANCE_VALUE> ::= 20 [0.2]
<ON_SCANNED_DISTANCE_VALUE> ::= 40 [0.2]
<ON_SCANNED_DISTANCE_VALUE> ::= 60 [0.2]
<ON_SCANNED_DISTANCE_VALUE> ::= 80 [0.2]
<ON_SCANNED_DISTANCE_VALUE> ::= distance [0.2]
<ON_SCANNED_DEGREES_VALUE> ::= 5 [0.2]
<ON_SCANNED_DEGREES_VALUE> ::= 15 [0.2]
<ON_SCANNED_DEGREES_VALUE> ::= 30 [0.2]
<ON_SCANNED_DEGREES_VALUE> ::= 45 [0.2]
<ON_SCANNED_DEGREES_VALUE> ::= bearing [0.2]

<ON_HIT_BY_BULLET_CODE_RULES_DEFAULT_ACTION> ::= <ON_HIT_BY_BULLET_CODE_RULES> default <ON_HIT_BY_BULLET_CODE_CONSEQUENTS> [1]
<ON_HIT_BY_BULLET_CODE_RULES> ::= <ON_HIT_BY_BULLET_CODE_RULE> [0.2]
<ON_HIT_BY_BULLET_CODE_RULES> ::= <ON_HIT_BY_BULLET_CODE_RULE> <ON_HIT_BY_BULLET_CODE_RULES> [0.8]
<ON_HIT_BY_BULLET_CODE_RULE> ::= if <ON_HIT_BY_BULLET_CODE_ANTECEDENTS> then <ON_HIT_BY_BULLET_CODE_CONSEQUENTS> [1]
<ON_HIT_BY_BULLET_CODE_ANTECEDENTS> ::= <ON_HIT_BY_BULLET_CODE_ANTECEDENT> [0.2]
<ON_HIT_BY_BULLET_CODE_ANTECEDENTS> ::= ( <ON_HIT_BY_BULLET_CODE_ANTECEDENT> <ON_HIT_BY_BULLET_CODE_OPR_ANTECEDENTS> <ON_HIT_BY_BULLET_CODE_ANTECEDENTS> ) [0.5]
<ON_HIT_BY_BULLET_CODE_ANTECEDENTS> ::= not ( <ON_HIT_BY_BULLET_CODE_ANTECEDENTS> ) [0.3]
<ON_HIT_BY_BULLET_CODE_ANTECEDENT> ::= bearing <ON_HIT_BY_BULLET_CODE_OPR_CLAUSE> <ON_HIT_BY_BULLET_CODE_CLAUSE_BEARING> [0.25]
<ON_HIT_BY_BULLET_CODE_OPR_CLAUSE> ::= > [0.5]
<ON_HIT_BY_BULLET_CODE_OPR_CLAUSE> ::= < [0.5]
<ON_HIT_BY_BULLET_CODE_CLAUSE_BEARING> ::= -120 [0.2]
<ON_HIT_BY_BULLET_CODE_CLAUSE_BEARING> ::= -60 [0.2]
<ON_HIT_BY_BULLET_CODE_CLAUSE_BEARING> ::= 0 [0.2]
<ON_HIT_BY_BULLET_CODE_CLAUSE_BEARING> ::= 60 [0.2]
<ON_HIT_BY_BULLET_CODE_CLAUSE_BEARING> ::= 120 [0.2]