<S> ::= <RUN_CODE_RULES_DEFAULT_ACTION> ### <ON_SCANNED_ROBOT_CODE_RULES_DEFAULT_ACTION>

<RUN_CODE_RULES_DEFAULT_ACTION> ::= <RUN_CODE_RULES> default <RUN_CODE_CONSEQUENTS>
<RUN_CODE_RULES> ::= <RUN_CODE_RULE> | <RUN_CODE_RULE> <RUN_CODE_RULES>
<RUN_CODE_RULE> ::= if <RUN_CODE_ANTECEDENTS> then <RUN_CODE_CONSEQUENTS>
<RUN_CODE_ANTECEDENTS> ::= <RUN_CODE_ANTECEDENT> | ( <RUN_CODE_ANTECEDENT> <RUN_CODE_OPR_ANTECEDENTS> <RUN_CODE_ANTECEDENTS> ) | not ( <RUN_CODE_ANTECEDENTS> )
<RUN_CODE_ANTECEDENT> ::= robot_x <RUN_CODE_OPR_CLAUSE> <RUN_CODE_CLAUSE_ROBOT_X> | robot_y <RUN_CODE_OPR_CLAUSE> <RUN_CODE_CLAUSE_ROBOT_Y> | robot_heading <RUN_CODE_OPR_CLAUSE> <RUN_CODE_CLAUSE_ROBOT_HEADING> | robot_velocity <RUN_CODE_OPR_CLAUSE> <RUN_CODE_CLAUSE_ROBOT_VELOCITY>
<RUN_CODE_OPR_CLAUSE> ::= > | <
<RUN_CODE_CLAUSE_ROBOT_X> ::= 0 | 200 | 400 | 600 | 800
<RUN_CODE_CLAUSE_ROBOT_Y> ::= 0 | 150 | 300 | 450 | 600
<RUN_CODE_CLAUSE_ROBOT_HEADING> ::= 0 | 90 | 180 | 270
<RUN_CODE_CLAUSE_ROBOT_VELOCITY> ::= -8 | -4 | 0 | 4 | 8
<RUN_CODE_OPR_ANTECEDENTS> ::= and | or
<RUN_CODE_CONSEQUENTS> ::= ahead <DISTANCE_VALUE> | back <DISTANCE_VALUE> | turn_right <DEGREES_VALUE> | turn_left <DEGREES_VALUE>
<DISTANCE_VALUE> ::= 20 | 40 | 60 | 80 | 100
<DEGREES_VALUE> ::= 5 | 15 | 30 | 45

<ON_SCANNED_ROBOT_CODE_RULES_DEFAULT_ACTION> ::= <ON_SCANNED_ROBOT_CODE_RULES> default <ON_SCANNED_ROBOT_CODE_CONSEQUENTS>
<ON_SCANNED_ROBOT_CODE_RULES> ::= <ON_SCANNED_ROBOT_CODE_RULE> | <ON_SCANNED_ROBOT_CODE_RULE> <ON_SCANNED_ROBOT_CODE_RULES>
<ON_SCANNED_ROBOT_CODE_RULE> ::= if <ON_SCANNED_ROBOT_CODE_ANTECEDENTS> then <ON_SCANNED_ROBOT_CODE_CONSEQUENTS>
<ON_SCANNED_ROBOT_CODE_ANTECEDENTS> ::= <ON_SCANNED_ROBOT_CODE_ANTECEDENT> | ( <ON_SCANNED_ROBOT_CODE_ANTECEDENT> <ON_SCANNED_ROBOT_CODE_OPR_ANTECEDENTS> <ON_SCANNED_ROBOT_CODE_ANTECEDENTS> ) | not ( <ON_SCANNED_ROBOT_CODE_ANTECEDENTS> )
<ON_SCANNED_ROBOT_CODE_ANTECEDENT> ::= distance <ON_SCANNED_ROBOT_CODE_OPR_CLAUSE> <ON_SCANNED_ROBOT_CODE_CLAUSE_DISTANCE> | energy <ON_SCANNED_ROBOT_CODE_OPR_CLAUSE> <ON_SCANNED_ROBOT_CODE_CLAUSE_ENERGY>
<ON_SCANNED_ROBOT_CODE_OPR_CLAUSE> ::= > | <
<ON_SCANNED_ROBOT_CODE_CLAUSE_DISTANCE> ::= 100 | 300 | 500 | 700
<ON_SCANNED_ROBOT_CODE_CLAUSE_ENERGY> ::= 10 | 30 | 50 | 70 | 90
<ON_SCANNED_ROBOT_CODE_OPR_ANTECEDENTS> ::= and | or
<ON_SCANNED_ROBOT_CODE_CONSEQUENTS> ::= fire <POWER_VALUE>
<POWER_VALUE> ::= 0.5 | 1 | 2 | 2.5 | 3

